version: '3.8'

services:
  db:
    image: ankane/pgvector:latest
    container_name: pgvector-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: godhitech
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
